In [1]:
import pandas as pd

import numpy as np

import warnings
warnings.filterwarnings('ignore')

### Interior

### Turistas interprovinciales por origen y destino de residentes en España

In [2]:
df = pd.read_excel('../interior/municipio_origen_destino.xlsx')
df

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-07,1001,Alegría-Dulantzi,12089,Peníscola/Peñíscola,34,1,Araba/Álava,12,Castellón/Castelló
1,2022-07,1001,Alegría-Dulantzi,20036,Hondarribia,40,1,Araba/Álava,20,Gipuzkoa
2,2022-07,1001,Alegría-Dulantzi,20069,Donostia/San Sebastián,48,1,Araba/Álava,20,Gipuzkoa
3,2022-07,1001,Alegría-Dulantzi,22199,Sabiñánigo,34,1,Araba/Álava,22,Huesca
4,2022-07,1001,Alegría-Dulantzi,28079,Madrid,48,1,Araba/Álava,28,Madrid
...,...,...,...,...,...,...,...,...,...,...
94504,2022-07,52001,Melilla,43905,Salou,32,52,Melilla,43,Tarragona
94505,2022-07,52001,Melilla,46250,València,125,52,Melilla,46,Valencia/València
94506,2022-07,52001,Melilla,48020,Bilbao,30,52,Melilla,48,Bizkaia
94507,2022-07,52001,Melilla,50297,Zaragoza,80,52,Melilla,50,Zaragoza
94508,2022-07,52001,Melilla,51001,Ceuta,99,52,Melilla,51,Ceuta

In [3]:
cambio_letras={'á': 'a', 'é': 'e', 'í': 'i', 'ó':'o', 'ú': 'u'}

def quitar_acentos(palabra):
    
    resultado=''
    
    palabra=palabra.lower()
    
    for letra in palabra:
        
        if letra in cambio_letras.keys():
            
            resultado+=cambio_letras[letra]
            
        else:
            resultado+=letra
            
    return resultado.capitalize()
            

df['mun_orig']=df['mun_orig'].apply(quitar_acentos)

df['mun_orig'].head()

0    Alegria-dulantzi
1    Alegria-dulantzi
2    Alegria-dulantzi
3    Alegria-dulantzi
4    Alegria-dulantzi
Name: mun_orig, dtype: object

In [4]:
df['dest']=df['dest'].apply(quitar_acentos)

In [5]:
df['prov_orig']=df['prov_orig'].apply(quitar_acentos)

In [6]:
df['prov_dest']=df['prov_dest'].apply(quitar_acentos)

In [7]:
df

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-07,1001,Alegria-dulantzi,12089,Peniscola/peñiscola,34,1,Araba/alava,12,Castellon/castello
1,2022-07,1001,Alegria-dulantzi,20036,Hondarribia,40,1,Araba/alava,20,Gipuzkoa
2,2022-07,1001,Alegria-dulantzi,20069,Donostia/san sebastian,48,1,Araba/alava,20,Gipuzkoa
3,2022-07,1001,Alegria-dulantzi,22199,Sabiñanigo,34,1,Araba/alava,22,Huesca
4,2022-07,1001,Alegria-dulantzi,28079,Madrid,48,1,Araba/alava,28,Madrid
...,...,...,...,...,...,...,...,...,...,...
94504,2022-07,52001,Melilla,43905,Salou,32,52,Melilla,43,Tarragona
94505,2022-07,52001,Melilla,46250,València,125,52,Melilla,46,Valencia/valència
94506,2022-07,52001,Melilla,48020,Bilbao,30,52,Melilla,48,Bizkaia
94507,2022-07,52001,Melilla,50297,Zaragoza,80,52,Melilla,50,Zaragoza
94508,2022-07,52001,Melilla,51001,Ceuta,99,52,Melilla,51,Ceuta

In [8]:
df['prov_orig_cod'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52], dtype=int64)

In [9]:
dic = {1:'ES-VI', 2:'ES-AB', 3:'ES-A', 4:'ES-AL', 5:'ES-AV', 6:'ES-BA', 7:'ES-PM', 8:'ES-B', 9:'ES-BU',
       10:'ES-C', 11:'ES-CA', 12:'ES-CS', 13:'ES-CR', 14:'ES-CO', 15:'ES-C', 16:'ES-CU', 17:'ES-GI', 18:'ES-GR', 19:'ES-GU', 
       20:'ES-SS', 21:'ES-H', 22:'ES-HU', 23:'ES-J', 24:'ES-LE', 25:'ES-L', 26:'ES-LO', 27:'ES-LU', 28:'ES-M', 29:'ES-MA',
       30:'ES-MU', 31:'ES-NA', 32:'ES-OR', 33:'ES-O', 34:'ES-P', 35:'ES-GC', 36:'ES-PO', 37:'ES-SA', 38:'ES-TF', 39:'ES-S',
       40:'ES-SG', 41:'ES-SE', 42:'ES-SO', 43:'ES-T', 44:'ES-TE', 45:'ES-TO', 46:'ES-V', 47:'ES-VA', 48:'ES-BI', 49:'ES-ZA',
       50:'ES-Z', 51:'ES-CE', 52:'ES-ML'}

In [10]:
df.replace({'prov_orig_cod':dic}, inplace=True)

In [11]:
df.replace({'prov_dest_cod':dic}, inplace=True)

In [12]:
df

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-07,1001,Alegria-dulantzi,12089,Peniscola/peñiscola,34,ES-VI,Araba/alava,ES-CS,Castellon/castello
1,2022-07,1001,Alegria-dulantzi,20036,Hondarribia,40,ES-VI,Araba/alava,ES-SS,Gipuzkoa
2,2022-07,1001,Alegria-dulantzi,20069,Donostia/san sebastian,48,ES-VI,Araba/alava,ES-SS,Gipuzkoa
3,2022-07,1001,Alegria-dulantzi,22199,Sabiñanigo,34,ES-VI,Araba/alava,ES-HU,Huesca
4,2022-07,1001,Alegria-dulantzi,28079,Madrid,48,ES-VI,Araba/alava,ES-M,Madrid
...,...,...,...,...,...,...,...,...,...,...
94504,2022-07,52001,Melilla,43905,Salou,32,ES-ML,Melilla,ES-T,Tarragona
94505,2022-07,52001,Melilla,46250,València,125,ES-ML,Melilla,ES-V,Valencia/valència
94506,2022-07,52001,Melilla,48020,Bilbao,30,ES-ML,Melilla,ES-BI,Bizkaia
94507,2022-07,52001,Melilla,50297,Zaragoza,80,ES-ML,Melilla,ES-Z,Zaragoza
94508,2022-07,52001,Melilla,51001,Ceuta,99,ES-ML,Melilla,ES-CE,Ceuta

In [13]:
df.mes.unique()

array(['2022-07'], dtype=object)

In [14]:
df.prov_dest_cod.unique()

array(['ES-CS', 'ES-SS', 'ES-HU', 'ES-M', 'ES-NA', 'ES-O', 'ES-S',
       'ES-BI', 'ES-A', 'ES-AV', 'ES-PM', 'ES-BU', 'ES-LO', 'ES-MA',
       'ES-T', 'ES-TO', 'ES-C', 'ES-GI', 'ES-OR', 'ES-P', 'ES-SA',
       'ES-VA', 'ES-ZA', 'ES-Z', 'ES-LE', 'ES-PO', 'ES-CA', 'ES-H',
       'ES-AL', 'ES-BA', 'ES-B', 'ES-CO', 'ES-GU', 'ES-MU', 'ES-SG',
       'ES-SE', 'ES-V', 'ES-AB', 'ES-CR', 'ES-CU', 'ES-GR', 'ES-J',
       'ES-L', 'ES-LU', 'ES-GC', 'ES-TF', 'ES-SO', 'ES-TE', 'ES-VI',
       'ES-CE', 'ES-ML'], dtype=object)

In [15]:
df.to_csv('interior_julio2022.csv', index=False)

In [16]:
junio2022 = pd.read_excel('../interior/interior2.xlsx')
junio2022

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-06,1001,Alegría-Dulantzi,20036,Hondarribia,32,1,Araba/Álava,20,Gipuzkoa
1,2022-06,1001,Alegría-Dulantzi,20069,Donostia/San Sebastián,87,1,Araba/Álava,20,Gipuzkoa
2,2022-06,1001,Alegría-Dulantzi,28079,Madrid,83,1,Araba/Álava,28,Madrid
3,2022-06,1001,Alegría-Dulantzi,31201,Pamplona/Iruña,39,1,Araba/Álava,31,Navarra
4,2022-06,1001,Alegría-Dulantzi,39047,Noja,52,1,Araba/Álava,39,Cantabria
...,...,...,...,...,...,...,...,...,...,...
74906,2022-06,52001,Melilla,46250,València,62,52,Melilla,46,Valencia/València
74907,2022-06,52001,Melilla,47186,Valladolid,52,52,Melilla,47,Valladolid
74908,2022-06,52001,Melilla,48020,Bilbao,36,52,Melilla,48,Bizkaia
74909,2022-06,52001,Melilla,50297,Zaragoza,75,52,Melilla,50,Zaragoza
74910,2022-06,52001,Melilla,51001,Ceuta,99,52,Melilla,51,Ceuta

In [17]:
junio2022['mun_orig']=junio2022['mun_orig'].apply(quitar_acentos)

In [18]:
junio2022['dest']=junio2022['dest'].apply(quitar_acentos)

In [19]:
junio2022['prov_orig']=junio2022['prov_orig'].apply(quitar_acentos)

In [20]:
junio2022['prov_dest']=junio2022['prov_dest'].apply(quitar_acentos)

In [21]:
junio2022.replace({'prov_orig_cod':dic}, inplace=True)

In [22]:
junio2022.replace({'prov_dest_cod':dic}, inplace=True)

In [23]:
junio2022

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-06,1001,Alegria-dulantzi,20036,Hondarribia,32,ES-VI,Araba/alava,ES-SS,Gipuzkoa
1,2022-06,1001,Alegria-dulantzi,20069,Donostia/san sebastian,87,ES-VI,Araba/alava,ES-SS,Gipuzkoa
2,2022-06,1001,Alegria-dulantzi,28079,Madrid,83,ES-VI,Araba/alava,ES-M,Madrid
3,2022-06,1001,Alegria-dulantzi,31201,Pamplona/iruña,39,ES-VI,Araba/alava,ES-NA,Navarra
4,2022-06,1001,Alegria-dulantzi,39047,Noja,52,ES-VI,Araba/alava,ES-S,Cantabria
...,...,...,...,...,...,...,...,...,...,...
74906,2022-06,52001,Melilla,46250,València,62,ES-ML,Melilla,ES-V,Valencia/valència
74907,2022-06,52001,Melilla,47186,Valladolid,52,ES-ML,Melilla,ES-VA,Valladolid
74908,2022-06,52001,Melilla,48020,Bilbao,36,ES-ML,Melilla,ES-BI,Bizkaia
74909,2022-06,52001,Melilla,50297,Zaragoza,75,ES-ML,Melilla,ES-Z,Zaragoza
74910,2022-06,52001,Melilla,51001,Ceuta,99,ES-ML,Melilla,ES-CE,Ceuta

In [24]:
junio2022.to_csv('interior_junio2022.csv', index=False)

In [25]:
mayo2022 = pd.read_excel('../interior/mayo2022.xlsx')
mayo2022

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-05,1001,Alegría-Dulantzi,8270,Sitges,45,1,Araba/Álava,8,Barcelona
1,2022-05,1001,Alegría-Dulantzi,20069,Donostia/San Sebastián,74,1,Araba/Álava,20,Gipuzkoa
2,2022-05,1001,Alegría-Dulantzi,28079,Madrid,74,1,Araba/Álava,28,Madrid
3,2022-05,1001,Alegría-Dulantzi,31201,Pamplona/Iruña,33,1,Araba/Álava,31,Navarra
4,2022-05,1001,Alegría-Dulantzi,43905,Salou,31,1,Araba/Álava,43,Tarragona
...,...,...,...,...,...,...,...,...,...,...
73985,2022-05,52001,Melilla,46250,València,43,52,Melilla,46,Valencia/València
73986,2022-05,52001,Melilla,50288,Villanueva de Gállego,37,52,Melilla,50,Zaragoza
73987,2022-05,52001,Melilla,50297,Zaragoza,113,52,Melilla,50,Zaragoza
73988,2022-05,52001,Melilla,50298,Zuera,118,52,Melilla,50,Zaragoza
73989,2022-05,52001,Melilla,51001,Ceuta,117,52,Melilla,51,Ceuta

In [26]:
mayo2022['mun_orig']=mayo2022['mun_orig'].apply(quitar_acentos)

In [27]:
mayo2022['dest']=mayo2022['dest'].apply(quitar_acentos)

In [28]:
mayo2022['prov_orig']=mayo2022['prov_orig'].apply(quitar_acentos)

In [29]:
mayo2022['prov_dest']=mayo2022['prov_dest'].apply(quitar_acentos)

In [30]:
mayo2022.replace({'prov_orig_cod':dic}, inplace=True)

In [31]:
mayo2022.replace({'prov_dest_cod':dic}, inplace=True)

In [32]:
mayo2022

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-05,1001,Alegria-dulantzi,8270,Sitges,45,ES-VI,Araba/alava,ES-B,Barcelona
1,2022-05,1001,Alegria-dulantzi,20069,Donostia/san sebastian,74,ES-VI,Araba/alava,ES-SS,Gipuzkoa
2,2022-05,1001,Alegria-dulantzi,28079,Madrid,74,ES-VI,Araba/alava,ES-M,Madrid
3,2022-05,1001,Alegria-dulantzi,31201,Pamplona/iruña,33,ES-VI,Araba/alava,ES-NA,Navarra
4,2022-05,1001,Alegria-dulantzi,43905,Salou,31,ES-VI,Araba/alava,ES-T,Tarragona
...,...,...,...,...,...,...,...,...,...,...
73985,2022-05,52001,Melilla,46250,València,43,ES-ML,Melilla,ES-V,Valencia/valència
73986,2022-05,52001,Melilla,50288,Villanueva de gallego,37,ES-ML,Melilla,ES-Z,Zaragoza
73987,2022-05,52001,Melilla,50297,Zaragoza,113,ES-ML,Melilla,ES-Z,Zaragoza
73988,2022-05,52001,Melilla,50298,Zuera,118,ES-ML,Melilla,ES-Z,Zaragoza
73989,2022-05,52001,Melilla,51001,Ceuta,117,ES-ML,Melilla,ES-CE,Ceuta

In [33]:
mayo2022.to_csv('interior_mayo2022.csv', index=False)

In [34]:
abril2022 = pd.read_excel('../interior/abril2022.xlsx')

In [35]:
abril2022['mun_orig']=abril2022['mun_orig'].apply(quitar_acentos)

In [36]:
abril2022['dest']=abril2022['dest'].apply(quitar_acentos)

In [37]:
abril2022['prov_orig']=abril2022['prov_orig'].apply(quitar_acentos)

In [38]:
abril2022['prov_dest']=abril2022['prov_dest'].apply(quitar_acentos)

In [39]:
abril2022.replace({'prov_orig_cod':dic}, inplace=True)

In [40]:
abril2022.replace({'prov_dest_cod':dic}, inplace=True)

In [41]:
abril2022

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-04,1001,Alegria-dulantzi,8019,Barcelona,39,ES-VI,Araba/alava,ES-B,Barcelona
1,2022-04,1001,Alegria-dulantzi,9124,Espinosa de los monteros,30,ES-VI,Araba/alava,ES-BU,Burgos
2,2022-04,1001,Alegria-dulantzi,20036,Hondarribia,37,ES-VI,Araba/alava,ES-SS,Gipuzkoa
3,2022-04,1001,Alegria-dulantzi,20069,Donostia/san sebastian,65,ES-VI,Araba/alava,ES-SS,Gipuzkoa
4,2022-04,1001,Alegria-dulantzi,28079,Madrid,106,ES-VI,Araba/alava,ES-M,Madrid
...,...,...,...,...,...,...,...,...,...,...
74762,2022-04,52001,Melilla,45168,Toledo,30,ES-ML,Melilla,ES-TO,Toledo
74763,2022-04,52001,Melilla,46250,València,71,ES-ML,Melilla,ES-V,Valencia/valència
74764,2022-04,52001,Melilla,48020,Bilbao,34,ES-ML,Melilla,ES-BI,Bizkaia
74765,2022-04,52001,Melilla,50297,Zaragoza,87,ES-ML,Melilla,ES-Z,Zaragoza
74766,2022-04,52001,Melilla,51001,Ceuta,107,ES-ML,Melilla,ES-CE,Ceuta

In [42]:
abril2022.to_csv('interior_abril2022.csv', index=False)

In [43]:
marzo2022 = pd.read_excel('../interior/marzo2022.xlsx')

In [44]:
marzo2022['mun_orig']=marzo2022['mun_orig'].apply(quitar_acentos)

In [45]:
marzo2022['dest']=marzo2022['dest'].apply(quitar_acentos)

In [46]:
marzo2022['prov_orig']=marzo2022['prov_orig'].apply(quitar_acentos)

In [47]:
marzo2022['prov_dest']=marzo2022['prov_dest'].apply(quitar_acentos)

In [48]:
marzo2022.replace({'prov_orig_cod':dic}, inplace=True)

In [49]:
marzo2022.replace({'prov_dest_cod':dic}, inplace=True)

In [50]:
marzo2022

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-03,1001,Alegria-dulantzi,9109,Condado de treviño,43,ES-VI,Araba/alava,ES-BU,Burgos
1,2022-03,1001,Alegria-dulantzi,20036,Hondarribia,31,ES-VI,Araba/alava,ES-SS,Gipuzkoa
2,2022-03,1001,Alegria-dulantzi,20069,Donostia/san sebastian,94,ES-VI,Araba/alava,ES-SS,Gipuzkoa
3,2022-03,1001,Alegria-dulantzi,21004,Almonaster la real,49,ES-VI,Araba/alava,ES-H,Huelva
4,2022-03,1001,Alegria-dulantzi,21060,Punta umbria,49,ES-VI,Araba/alava,ES-H,Huelva
...,...,...,...,...,...,...,...,...,...,...
54915,2022-03,52001,Melilla,50235,San mateo de gallego,174,ES-ML,Melilla,ES-Z,Zaragoza
54916,2022-03,52001,Melilla,50288,Villanueva de gallego,277,ES-ML,Melilla,ES-Z,Zaragoza
54917,2022-03,52001,Melilla,50297,Zaragoza,137,ES-ML,Melilla,ES-Z,Zaragoza
54918,2022-03,52001,Melilla,50298,Zuera,131,ES-ML,Melilla,ES-Z,Zaragoza
54919,2022-03,52001,Melilla,51001,Ceuta,112,ES-ML,Melilla,ES-CE,Ceuta

In [51]:
marzo2022.to_csv('interior_marzo2022.csv', index=False)

In [52]:
febrero2022 = pd.read_excel('../interior/febrero2022.xlsx')

In [53]:
febrero2022['mun_orig']=febrero2022['mun_orig'].apply(quitar_acentos)

In [54]:
febrero2022['dest']=febrero2022['dest'].apply(quitar_acentos)

In [55]:
febrero2022['prov_orig']=febrero2022['prov_orig'].apply(quitar_acentos)

In [56]:
febrero2022['prov_dest']=febrero2022['prov_dest'].apply(quitar_acentos)

In [57]:
febrero2022.replace({'prov_orig_cod':dic}, inplace=True)

In [58]:
febrero2022.replace({'prov_dest_cod':dic}, inplace=True)

In [59]:
febrero2022

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-02,1001,Alegria-dulantzi,9219,Miranda de ebro,32,ES-VI,Araba/alava,ES-BU,Burgos
1,2022-02,1001,Alegria-dulantzi,20069,Donostia/san sebastian,93,ES-VI,Araba/alava,ES-SS,Gipuzkoa
2,2022-02,1001,Alegria-dulantzi,26089,Logroño,32,ES-VI,Araba/alava,ES-LO,"Rioja, la"
3,2022-02,1001,Alegria-dulantzi,28079,Madrid,48,ES-VI,Araba/alava,ES-M,Madrid
4,2022-02,1001,Alegria-dulantzi,48020,Bilbao,39,ES-VI,Araba/alava,ES-BI,Bizkaia
...,...,...,...,...,...,...,...,...,...,...
46293,2022-02,52001,Melilla,41091,Sevilla,260,ES-ML,Melilla,ES-SE,Sevilla
46294,2022-02,52001,Melilla,45168,Toledo,31,ES-ML,Melilla,ES-TO,Toledo
46295,2022-02,52001,Melilla,46250,València,87,ES-ML,Melilla,ES-V,Valencia/valència
46296,2022-02,52001,Melilla,50297,Zaragoza,78,ES-ML,Melilla,ES-Z,Zaragoza
46297,2022-02,52001,Melilla,51001,Ceuta,73,ES-ML,Melilla,ES-CE,Ceuta

In [60]:
febrero2022.to_csv('interior_febrero2022.csv', index=False)

In [61]:
enero2022 = pd.read_excel('../interior/enero2022.xlsx')

In [62]:
enero2022['mun_orig']=enero2022['mun_orig'].apply(quitar_acentos)

In [63]:
enero2022['dest']=enero2022['dest'].apply(quitar_acentos)

In [64]:
enero2022['prov_orig']=enero2022['prov_orig'].apply(quitar_acentos)

In [65]:
enero2022['prov_dest']=enero2022['prov_dest'].apply(quitar_acentos)

In [66]:
enero2022.replace({'prov_orig_cod':dic}, inplace=True)

In [67]:
enero2022.replace({'prov_dest_cod':dic}, inplace=True)

In [68]:
enero2022

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2022-01,1001,Alegria-dulantzi,20069,Donostia/san sebastian,91,ES-VI,Araba/alava,ES-SS,Gipuzkoa
1,2022-01,1001,Alegria-dulantzi,22199,Sabiñanigo,34,ES-VI,Araba/alava,ES-HU,Huesca
2,2022-01,1001,Alegria-dulantzi,24089,Leon,41,ES-VI,Araba/alava,ES-LE,Leon
3,2022-01,1001,Alegria-dulantzi,26089,Logroño,30,ES-VI,Araba/alava,ES-LO,"Rioja, la"
4,2022-01,1001,Alegria-dulantzi,28079,Madrid,96,ES-VI,Araba/alava,ES-M,Madrid
...,...,...,...,...,...,...,...,...,...,...
52963,2022-01,52001,Melilla,45052,Cobisa,37,ES-ML,Melilla,ES-TO,Toledo
52964,2022-01,52001,Melilla,45168,Toledo,63,ES-ML,Melilla,ES-TO,Toledo
52965,2022-01,52001,Melilla,46250,València,93,ES-ML,Melilla,ES-V,Valencia/valència
52966,2022-01,52001,Melilla,50297,Zaragoza,66,ES-ML,Melilla,ES-Z,Zaragoza
52967,2022-01,52001,Melilla,51001,Ceuta,99,ES-ML,Melilla,ES-CE,Ceuta

In [69]:
enero2022.to_csv('interior_enero2022.csv', index=False)

In [70]:
diciembre2021 = pd.read_excel('../interior/diciembre2021.xlsx')

In [71]:
diciembre2021['mun_orig']=diciembre2021['mun_orig'].apply(quitar_acentos)

In [72]:
diciembre2021['dest']=diciembre2021['dest'].apply(quitar_acentos)

In [73]:
diciembre2021['prov_orig']=diciembre2021['prov_orig'].apply(quitar_acentos)

In [74]:
diciembre2021['prov_dest']=diciembre2021['prov_dest'].apply(quitar_acentos)

In [75]:
diciembre2021.replace({'prov_orig_cod':dic}, inplace=True)

In [76]:
diciembre2021.replace({'prov_dest_cod':dic}, inplace=True)

In [77]:
diciembre2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-12,1001,Alegria-dulantzi,20069,Donostia/san sebastian,121,ES-VI,Araba/alava,ES-SS,Gipuzkoa
1,2021-12,1001,Alegria-dulantzi,28079,Madrid,75,ES-VI,Araba/alava,ES-M,Madrid
2,2021-12,1001,Alegria-dulantzi,31201,Pamplona/iruña,34,ES-VI,Araba/alava,ES-NA,Navarra
3,2021-12,1001,Alegria-dulantzi,48020,Bilbao,39,ES-VI,Araba/alava,ES-BI,Bizkaia
4,2021-12,1002,Amurrio,8019,Barcelona,41,ES-VI,Araba/alava,ES-B,Barcelona
...,...,...,...,...,...,...,...,...,...,...
63396,2021-12,52001,Melilla,43148,Tarragona,32,ES-ML,Melilla,ES-T,Tarragona
63397,2021-12,52001,Melilla,46250,València,98,ES-ML,Melilla,ES-V,Valencia/valència
63398,2021-12,52001,Melilla,47186,Valladolid,60,ES-ML,Melilla,ES-VA,Valladolid
63399,2021-12,52001,Melilla,50297,Zaragoza,134,ES-ML,Melilla,ES-Z,Zaragoza
63400,2021-12,52001,Melilla,51001,Ceuta,88,ES-ML,Melilla,ES-CE,Ceuta

In [78]:
diciembre2021.to_csv('interior_diciembre2021.csv', index=False)

In [79]:
noviembre2021 = pd.read_excel('../interior/noviembre2021.xlsx')

In [80]:
noviembre2021['mun_orig']=noviembre2021['mun_orig'].apply(quitar_acentos)

In [81]:
noviembre2021['dest']=noviembre2021['dest'].apply(quitar_acentos)

In [82]:
noviembre2021['prov_orig']=noviembre2021['prov_orig'].apply(quitar_acentos)

In [83]:
noviembre2021['prov_dest']=noviembre2021['prov_dest'].apply(quitar_acentos)

In [84]:
noviembre2021.replace({'prov_orig_cod':dic}, inplace=True)

In [85]:
noviembre2021.replace({'prov_dest_cod':dic}, inplace=True)

In [86]:
noviembre2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-11,1001,Alegria-dulantzi,20069,Donostia/san sebastian,67,ES-VI,Araba/alava,ES-SS,Gipuzkoa
1,2021-11,1001,Alegria-dulantzi,28079,Madrid,98,ES-VI,Araba/alava,ES-M,Madrid
2,2021-11,1001,Alegria-dulantzi,48020,Bilbao,35,ES-VI,Araba/alava,ES-BI,Bizkaia
3,2021-11,1002,Amurrio,3031,Benidorm,59,ES-VI,Araba/alava,ES-A,Alicante/alacant
4,2021-11,1002,Amurrio,8019,Barcelona,41,ES-VI,Araba/alava,ES-B,Barcelona
...,...,...,...,...,...,...,...,...,...,...
64636,2021-11,52001,Melilla,43148,Tarragona,35,ES-ML,Melilla,ES-T,Tarragona
64637,2021-11,52001,Melilla,45168,Toledo,50,ES-ML,Melilla,ES-TO,Toledo
64638,2021-11,52001,Melilla,46250,València,130,ES-ML,Melilla,ES-V,Valencia/valència
64639,2021-11,52001,Melilla,50297,Zaragoza,70,ES-ML,Melilla,ES-Z,Zaragoza
64640,2021-11,52001,Melilla,51001,Ceuta,114,ES-ML,Melilla,ES-CE,Ceuta

In [87]:
noviembre2021.to_csv('interior_noviembre2021.csv', index=False)

In [88]:
octubre2021 = pd.read_excel('../interior/octubre2021.xlsx')

In [89]:
octubre2021['mun_orig']=octubre2021['mun_orig'].apply(quitar_acentos)

In [90]:
octubre2021['dest']=octubre2021['dest'].apply(quitar_acentos)

In [91]:
octubre2021['prov_orig']=octubre2021['prov_orig'].apply(quitar_acentos)

In [92]:
octubre2021['prov_dest']=octubre2021['prov_dest'].apply(quitar_acentos)

In [93]:
octubre2021.replace({'prov_orig_cod':dic}, inplace=True)

In [94]:
octubre2021.replace({'prov_dest_cod':dic}, inplace=True)

In [95]:
octubre2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-10,1001,Alegria-dulantzi,20055,Arrasate/mondragon,37,ES-VI,Araba/alava,ES-SS,Gipuzkoa
1,2021-10,1001,Alegria-dulantzi,20069,Donostia/san sebastian,78,ES-VI,Araba/alava,ES-SS,Gipuzkoa
2,2021-10,1001,Alegria-dulantzi,28079,Madrid,54,ES-VI,Araba/alava,ES-M,Madrid
3,2021-10,1001,Alegria-dulantzi,48020,Bilbao,37,ES-VI,Araba/alava,ES-BI,Bizkaia
4,2021-10,1002,Amurrio,3031,Benidorm,37,ES-VI,Araba/alava,ES-A,Alicante/alacant
...,...,...,...,...,...,...,...,...,...,...
75139,2021-10,52001,Melilla,47186,Valladolid,57,ES-ML,Melilla,ES-VA,Valladolid
75140,2021-10,52001,Melilla,48020,Bilbao,53,ES-ML,Melilla,ES-BI,Bizkaia
75141,2021-10,52001,Melilla,50288,Villanueva de gallego,38,ES-ML,Melilla,ES-Z,Zaragoza
75142,2021-10,52001,Melilla,50297,Zaragoza,81,ES-ML,Melilla,ES-Z,Zaragoza
75143,2021-10,52001,Melilla,51001,Ceuta,75,ES-ML,Melilla,ES-CE,Ceuta

In [96]:
octubre2021.to_csv('interior_octubre2021.csv', index=False)

In [97]:
septiembre2021 = pd.read_excel('../interior/septiembre2021.xlsx')

In [98]:
septiembre2021['mun_orig']=septiembre2021['mun_orig'].apply(quitar_acentos)

In [99]:
septiembre2021['dest']=septiembre2021['dest'].apply(quitar_acentos)

In [100]:
septiembre2021['prov_orig']=septiembre2021['prov_orig'].apply(quitar_acentos)

In [101]:
septiembre2021['prov_dest']=septiembre2021['prov_dest'].apply(quitar_acentos)

In [102]:
septiembre2021.replace({'prov_orig_cod':dic}, inplace=True)

In [103]:
septiembre2021.replace({'prov_dest_cod':dic}, inplace=True)

In [104]:
septiembre2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-09,1001,Alegria-dulantzi,20013,Aretxabaleta,31,ES-VI,Araba/alava,ES-SS,Gipuzkoa
1,2021-09,1001,Alegria-dulantzi,20069,Donostia/san sebastian,71,ES-VI,Araba/alava,ES-SS,Gipuzkoa
2,2021-09,1001,Alegria-dulantzi,28079,Madrid,53,ES-VI,Araba/alava,ES-M,Madrid
3,2021-09,1001,Alegria-dulantzi,31201,Pamplona/iruña,30,ES-VI,Araba/alava,ES-NA,Navarra
4,2021-09,1001,Alegria-dulantzi,39020,Castro-urdiales,40,ES-VI,Araba/alava,ES-S,Cantabria
...,...,...,...,...,...,...,...,...,...,...
80586,2021-09,52001,Melilla,46250,València,76,ES-ML,Melilla,ES-V,Valencia/valència
80587,2021-09,52001,Melilla,47186,Valladolid,62,ES-ML,Melilla,ES-VA,Valladolid
80588,2021-09,52001,Melilla,48020,Bilbao,72,ES-ML,Melilla,ES-BI,Bizkaia
80589,2021-09,52001,Melilla,50297,Zaragoza,79,ES-ML,Melilla,ES-Z,Zaragoza
80590,2021-09,52001,Melilla,51001,Ceuta,68,ES-ML,Melilla,ES-CE,Ceuta

In [105]:
septiembre2021.to_csv('interior_septiembre2021.csv', index=False)

In [106]:
agosto2021 = pd.read_excel('../interior/agosto2021.xlsx')

In [107]:
agosto2021['mun_orig']=agosto2021['mun_orig'].apply(quitar_acentos)

In [108]:
agosto2021['dest']=agosto2021['dest'].apply(quitar_acentos)

In [109]:
agosto2021['prov_orig']=agosto2021['prov_orig'].apply(quitar_acentos)

In [110]:
agosto2021['prov_dest']=agosto2021['prov_dest'].apply(quitar_acentos)

In [111]:
agosto2021.replace({'prov_orig_cod':dic}, inplace=True)

In [112]:
agosto2021.replace({'prov_dest_cod':dic}, inplace=True)

In [113]:
agosto2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-08,1001,Alegria-dulantzi,3031,Benidorm,42,ES-VI,Araba/alava,ES-A,Alicante/alacant
1,2021-08,1001,Alegria-dulantzi,20036,Hondarribia,30,ES-VI,Araba/alava,ES-SS,Gipuzkoa
2,2021-08,1001,Alegria-dulantzi,20069,Donostia/san sebastian,84,ES-VI,Araba/alava,ES-SS,Gipuzkoa
3,2021-08,1001,Alegria-dulantzi,28079,Madrid,34,ES-VI,Araba/alava,ES-M,Madrid
4,2021-08,1001,Alegria-dulantzi,39006,Arnuero,31,ES-VI,Araba/alava,ES-S,Cantabria
...,...,...,...,...,...,...,...,...,...,...
108495,2021-08,52001,Melilla,46105,Cullera,57,ES-ML,Melilla,ES-V,Valencia/valència
108496,2021-08,52001,Melilla,46250,València,146,ES-ML,Melilla,ES-V,Valencia/valència
108497,2021-08,52001,Melilla,48020,Bilbao,46,ES-ML,Melilla,ES-BI,Bizkaia
108498,2021-08,52001,Melilla,50297,Zaragoza,55,ES-ML,Melilla,ES-Z,Zaragoza
108499,2021-08,52001,Melilla,51001,Ceuta,88,ES-ML,Melilla,ES-CE,Ceuta

In [114]:
agosto2021.to_csv('interior_agosto2021.csv', index=False)

In [115]:
julio2021 = pd.read_excel('../interior/julio2021.xlsx')

In [116]:
julio2021['mun_orig']=julio2021['mun_orig'].apply(quitar_acentos)

In [117]:
julio2021['dest']=julio2021['dest'].apply(quitar_acentos)

In [118]:
julio2021['prov_orig']=julio2021['prov_orig'].apply(quitar_acentos)

In [119]:
julio2021['prov_dest']=julio2021['prov_dest'].apply(quitar_acentos)

In [120]:
julio2021.replace({'prov_orig_cod':dic}, inplace=True)

In [121]:
julio2021.replace({'prov_dest_cod':dic}, inplace=True)

In [122]:
julio2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-07,1001,Alegria-dulantzi,20055,Arrasate/mondragon,32,ES-VI,Araba/alava,ES-SS,Gipuzkoa
1,2021-07,1001,Alegria-dulantzi,20069,Donostia/san sebastian,83,ES-VI,Araba/alava,ES-SS,Gipuzkoa
2,2021-07,1001,Alegria-dulantzi,28079,Madrid,51,ES-VI,Araba/alava,ES-M,Madrid
3,2021-07,1001,Alegria-dulantzi,39006,Arnuero,34,ES-VI,Araba/alava,ES-S,Cantabria
4,2021-07,1001,Alegria-dulantzi,39020,Castro-urdiales,41,ES-VI,Araba/alava,ES-S,Cantabria
...,...,...,...,...,...,...,...,...,...,...
88487,2021-07,52001,Melilla,45168,Toledo,44,ES-ML,Melilla,ES-TO,Toledo
88488,2021-07,52001,Melilla,46105,Cullera,70,ES-ML,Melilla,ES-V,Valencia/valència
88489,2021-07,52001,Melilla,46250,València,111,ES-ML,Melilla,ES-V,Valencia/valència
88490,2021-07,52001,Melilla,50297,Zaragoza,37,ES-ML,Melilla,ES-Z,Zaragoza
88491,2021-07,52001,Melilla,51001,Ceuta,91,ES-ML,Melilla,ES-CE,Ceuta

In [123]:
julio2021.to_csv('interior_julio2021.csv', index=False)

In [124]:
junio2021 = pd.read_excel('../interior/junio2021.xlsx')

In [125]:
junio2021['mun_orig']=junio2021['mun_orig'].apply(quitar_acentos)

In [126]:
junio2021['dest']=junio2021['dest'].apply(quitar_acentos)

In [127]:
junio2021['prov_orig']=junio2021['prov_orig'].apply(quitar_acentos)

In [128]:
junio2021['prov_dest']=junio2021['prov_dest'].apply(quitar_acentos)

In [129]:
junio2021.replace({'prov_dest_cod':dic}, inplace=True)

In [130]:
junio2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-06,1001,Alegria-dulantzi,20069,Donostia/san sebastian,62,1,Araba/alava,ES-SS,Gipuzkoa
1,2021-06,1001,Alegria-dulantzi,28079,Madrid,41,1,Araba/alava,ES-M,Madrid
2,2021-06,1001,Alegria-dulantzi,39047,Noja,32,1,Araba/alava,ES-S,Cantabria
3,2021-06,1002,Amurrio,3031,Benidorm,31,1,Araba/alava,ES-A,Alicante/alacant
4,2021-06,1002,Amurrio,9190,Junta de villalba de losa,124,1,Araba/alava,ES-BU,Burgos
...,...,...,...,...,...,...,...,...,...,...
73581,2021-06,52001,Melilla,43148,Tarragona,34,52,Melilla,ES-T,Tarragona
73582,2021-06,52001,Melilla,46250,València,85,52,Melilla,ES-V,Valencia/valència
73583,2021-06,52001,Melilla,47186,Valladolid,49,52,Melilla,ES-VA,Valladolid
73584,2021-06,52001,Melilla,50297,Zaragoza,49,52,Melilla,ES-Z,Zaragoza
73585,2021-06,52001,Melilla,51001,Ceuta,57,52,Melilla,ES-CE,Ceuta

In [131]:
junio2021.to_csv('interior_junio2021.csv', index=False)

In [132]:
mayo2021 = pd.read_excel('../interior/mayo2021.xlsx')

In [133]:
mayo2021['mun_orig']=mayo2021['mun_orig'].apply(quitar_acentos)

In [134]:
mayo2021['dest']=mayo2021['dest'].apply(quitar_acentos)

In [135]:
mayo2021['prov_orig']=mayo2021['prov_orig'].apply(quitar_acentos)

In [136]:
mayo2021['prov_dest']=mayo2021['prov_dest'].apply(quitar_acentos)

In [137]:
mayo2021.replace({'prov_dest_cod':dic}, inplace=True)

In [138]:
mayo2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-05,1001,Alegria-dulantzi,20069,Donostia/san sebastian,58,1,Araba/alava,ES-SS,Gipuzkoa
1,2021-05,1001,Alegria-dulantzi,28079,Madrid,65,1,Araba/alava,ES-M,Madrid
2,2021-05,1002,Amurrio,9190,Junta de villalba de losa,110,1,Araba/alava,ES-BU,Burgos
3,2021-05,1002,Amurrio,9219,Miranda de ebro,32,1,Araba/alava,ES-BU,Burgos
4,2021-05,1002,Amurrio,9238,Oña,33,1,Araba/alava,ES-BU,Burgos
...,...,...,...,...,...,...,...,...,...,...
60476,2021-05,52001,Melilla,41091,Sevilla,214,52,Melilla,ES-SE,Sevilla
60477,2021-05,52001,Melilla,46250,València,46,52,Melilla,ES-V,Valencia/valència
60478,2021-05,52001,Melilla,47186,Valladolid,45,52,Melilla,ES-VA,Valladolid
60479,2021-05,52001,Melilla,50297,Zaragoza,81,52,Melilla,ES-Z,Zaragoza
60480,2021-05,52001,Melilla,51001,Ceuta,55,52,Melilla,ES-CE,Ceuta

In [139]:
mayo2021.to_csv('interior_mayo2021.csv', index=False)

In [140]:
abril2021 = pd.read_excel('../interior/abril2021.xlsx')

In [141]:
abril2021['mun_orig']=abril2021['mun_orig'].apply(quitar_acentos)

In [142]:
abril2021['dest']=abril2021['dest'].apply(quitar_acentos)

In [143]:
abril2021['prov_orig']=abril2021['prov_orig'].apply(quitar_acentos)

In [144]:
abril2021['prov_dest']=abril2021['prov_dest'].apply(quitar_acentos)

In [145]:
abril2021.replace({'prov_dest_cod':dic}, inplace=True)

In [146]:
abril2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-04,1001,Alegria-dulantzi,20069,Donostia/san sebastian,74,1,Araba/alava,ES-SS,Gipuzkoa
1,2021-04,1001,Alegria-dulantzi,48020,Bilbao,36,1,Araba/alava,ES-BI,Bizkaia
2,2021-04,1002,Amurrio,9190,Junta de villalba de losa,115,1,Araba/alava,ES-BU,Burgos
3,2021-04,1002,Amurrio,9410,Valle de mena,55,1,Araba/alava,ES-BU,Burgos
4,2021-04,1002,Amurrio,17023,Blanes,34,1,Araba/alava,ES-GI,Girona
...,...,...,...,...,...,...,...,...,...,...
42791,2021-04,52001,Melilla,46005,Alaquàs,30,52,Melilla,ES-V,Valencia/valència
42792,2021-04,52001,Melilla,46145,Xàtiva,42,52,Melilla,ES-V,Valencia/valència
42793,2021-04,52001,Melilla,46250,València,68,52,Melilla,ES-V,Valencia/valència
42794,2021-04,52001,Melilla,50297,Zaragoza,61,52,Melilla,ES-Z,Zaragoza
42795,2021-04,52001,Melilla,51001,Ceuta,88,52,Melilla,ES-CE,Ceuta

In [147]:
abril2021.to_csv('interior_abril2021.csv', index=False)

In [148]:
marzo2021 = pd.read_excel('../interior/marzo2021.xlsx')

In [149]:
marzo2021['mun_orig']=marzo2021['mun_orig'].apply(quitar_acentos)

In [150]:
marzo2021['dest']=marzo2021['dest'].apply(quitar_acentos)

In [151]:
marzo2021['prov_orig']=marzo2021['prov_orig'].apply(quitar_acentos)

In [152]:
marzo2021['prov_dest']=marzo2021['prov_dest'].apply(quitar_acentos)

In [153]:
marzo2021.replace({'prov_dest_cod':dic}, inplace=True)

In [154]:
marzo2021

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-03,1001,Alegria-dulantzi,20069,Donostia/san sebastian,73,1,Araba/alava,ES-SS,Gipuzkoa
1,2021-03,1001,Alegria-dulantzi,28079,Madrid,48,1,Araba/alava,ES-M,Madrid
2,2021-03,1001,Alegria-dulantzi,48020,Bilbao,33,1,Araba/alava,ES-BI,Bizkaia
3,2021-03,1002,Amurrio,9190,Junta de villalba de losa,108,1,Araba/alava,ES-BU,Burgos
4,2021-03,1002,Amurrio,9410,Valle de mena,53,1,Araba/alava,ES-BU,Burgos
...,...,...,...,...,...,...,...,...,...,...
40817,2021-03,52001,Melilla,41091,Sevilla,349,52,Melilla,ES-SE,Sevilla
40818,2021-03,52001,Melilla,41093,Tomares,38,52,Melilla,ES-SE,Sevilla
40819,2021-03,52001,Melilla,46250,València,62,52,Melilla,ES-V,Valencia/valència
40820,2021-03,52001,Melilla,50297,Zaragoza,41,52,Melilla,ES-Z,Zaragoza
40821,2021-03,52001,Melilla,51001,Ceuta,73,52,Melilla,ES-CE,Ceuta

In [155]:
marzo2021.to_csv('interior_marzo2021.csv', index=False)

### Concatenar

In [164]:
interior = pd.concat([marzo2021, abril2021, mayo2021, junio2021, julio2021, agosto2021, septiembre2021, octubre2021, noviembre2021, diciembre2021, enero2022, febrero2022, marzo2022, abril2022, mayo2022, junio2022, df], axis = 0)

In [165]:
interior

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest
0,2021-03,1001,Alegria-dulantzi,20069,Donostia/san sebastian,73,1,Araba/alava,ES-SS,Gipuzkoa
1,2021-03,1001,Alegria-dulantzi,28079,Madrid,48,1,Araba/alava,ES-M,Madrid
2,2021-03,1001,Alegria-dulantzi,48020,Bilbao,33,1,Araba/alava,ES-BI,Bizkaia
3,2021-03,1002,Amurrio,9190,Junta de villalba de losa,108,1,Araba/alava,ES-BU,Burgos
4,2021-03,1002,Amurrio,9410,Valle de mena,53,1,Araba/alava,ES-BU,Burgos
...,...,...,...,...,...,...,...,...,...,...
94504,2022-07,52001,Melilla,43905,Salou,32,ES-ML,Melilla,ES-T,Tarragona
94505,2022-07,52001,Melilla,46250,València,125,ES-ML,Melilla,ES-V,Valencia/valència
94506,2022-07,52001,Melilla,48020,Bilbao,30,ES-ML,Melilla,ES-BI,Bizkaia
94507,2022-07,52001,Melilla,50297,Zaragoza,80,ES-ML,Melilla,ES-Z,Zaragoza
94508,2022-07,52001,Melilla,51001,Ceuta,99,ES-ML,Melilla,ES-CE,Ceuta

In [167]:
interior.to_csv('innterior.csv', index=False)

In [168]:
interior['fecha'] = interior.mes
interior

,mes,mun_orig_cod,mun_orig,dest_cod,dest,turistas,prov_orig_cod,prov_orig,prov_dest_cod,prov_dest,fecha
0,2021-03,1001,Alegria-dulantzi,20069,Donostia/san sebastian,73,1,Araba/alava,ES-SS,Gipuzkoa,2021-03
1,2021-03,1001,Alegria-dulantzi,28079,Madrid,48,1,Araba/alava,ES-M,Madrid,2021-03
2,2021-03,1001,Alegria-dulantzi,48020,Bilbao,33,1,Araba/alava,ES-BI,Bizkaia,2021-03
3,2021-03,1002,Amurrio,9190,Junta de villalba de losa,108,1,Araba/alava,ES-BU,Burgos,2021-03
4,2021-03,1002,Amurrio,9410,Valle de mena,53,1,Araba/alava,ES-BU,Burgos,2021-03
...,...,...,...,...,...,...,...,...,...,...,...
94504,2022-07,52001,Melilla,43905,Salou,32,ES-ML,Melilla,ES-T,Tarragona,2022-07
94505,2022-07,52001,Melilla,46250,València,125,ES-ML,Melilla,ES-V,Valencia/valència,2022-07
94506,2022-07,52001,Melilla,48020,Bilbao,30,ES-ML,Melilla,ES-BI,Bizkaia,2022-07
94507,2022-07,52001,Melilla,50297,Zaragoza,80,ES-ML,Melilla,ES-Z,Zaragoza,2022-07
94508,2022-07,52001,Melilla,51001,Ceuta,99,ES-ML,Melilla,ES-CE,Ceuta,2022-07

In [169]:
interior.to_csv('interior.csv', index=False)